### ISSUE TITLE
Custom scrubFields aren't merged with default scrubFields

### ISSUE THREAD

**Issue by gbakernet** [rollbar/rollbar.js#647] opened 2018-07-20 03:16 UTC
Using rollbar 2.4.1

## What happens

When you list a custom set of scrubFields in an array. It isn't merged with the default list. 

```
scrubFields: ["token"]
```

Results found in Rollbar dashboard with testing with custom scrubFields
```
http://localhost/?password=1234&username=1233&lang=en&token=********
```

Results found in Rollbar dashboard with testing without custom scrubFields
```
http://localhost:3500/?password=********&username=1233&lang=en
```

## Expected

I believe it is reasonable to expect that they are merged.

```
scrubFields: ["token", ...theDefaultScrubFields]
```

Results found in Rollbar dashboard should be
```
http://localhost/?password=********&username=1233&lang=en&token=********
```

## Cause

I tracked the issue down to the merge function with doesn't support deep merging arrays.

**Comment by rokob** [comment] 2018-07-27 21:19
This is sorta kinda by design. So the original way this worked was that the arrays were merged but incorrectly (due to JS being JS what actually happened was that your new array overwrote the beginning of the currently set array up to the length of the new array). So I changed that extremely odd behaviour to replacing the array with what you set rather than merging.

Why? Well while one person might expect

```
scrubFields: ["token"]
```

to correspond to

```
scrubFields: ["token", ...theDefaultScrubFields]
```

However, how does one then not scrub a field that is in the default scrub fields set? There are two possibilities. 1) Add a whitelist of fields to not scrub even if they are in scrub fields. 2) If you set `scrub_fields` then you set it to exactly what you want, which would need to include whatever might have been in there by default.

I went with the second choice as it seemed the most parsimonious. Not sure how others feel.

**Comment by gbakernet** [comment] 2018-07-29 23:34
@rokob Sounds like a sensible trade off. Perhaps the only thing to do would be to mention in the docs that the defaults will be overridden?

**Comment by blimpage** [comment] 2018-08-07 00:28
Two cents from another user: I suspect it's a more common use case that users would want to add entries to `scrubFields` rather than remove them. Personally I'd be fine with having to explicitly specify any default values that I no longer want scrubbed.

Either way I was surprised that the behaviour changed without being mentioned in a changelog or a deprecation warning, even if it wasn't previously working as intended.

**Comment by jessewgibbs** [comment] 2018-10-09 23:52
I've updated the docs to reflect the current behavior.  Leaving this issue open as an `enhancement` in our backlog so we can revisit the behavior and make it easier to append/remove from the default array.

**Comment by rokob** [comment] 2018-11-27 22:03
There is now a way to control this, see the release notes for 2.5.0: https://github.com/rollbar/rollbar.js/releases/tag/v2.5.0

**Closed by rokob** 2018-11-27 22:03 UTC
Labels: enhancement
