### ISSUE TITLE
Uncaught TypeError: Cannot set property 'impl' of null

### ISSUE THREAD

**Issue by JasonSooter** [rollbar/rollbar.js#480] opened 2017-10-30 15:58 UTC
I am receiving this error in the console with the rollbar script on our site. It's a Magento site. The error points column 5438 of line 234(the line of the rollbar script). 

Support told me to leave a message here. 

Our site is https://www.theorganicbloom.com.

Let me know if I can be of any assistance

**Comment by rivkahstandig3636** [comment] 2017-12-05 13:04
This is a duplicate of issue #344. I recommend commenting and following that issue, as I'll close this so as not to have multiples of the same issue.

**Closed by rivkahstandig3636** 2017-12-05 13:04 UTC
