### ISSUE TITLE
"$remote_ip" as `user_ip` isn't replaced with actual ip address

### ISSUE THREAD

**Issue by mitchhentges** [rollbar/rollbar.js#165] opened 2015-12-18 00:37 UTC
We're currently upgrading to Rollbar 1.8.0, and in Rollbar requests made to the server, I'm seeing that `body.request.user_ip` is always "$remote_ip".

I've tested from an Android device (from a WebView) and via Chrome itself. Either way, "remote_ip" isn't filled in.

See [this gist](https://gist.github.com/mitchhentges/94dfd1db773fe8efda54).
![rollbar](https://cloud.githubusercontent.com/assets/7784737/11886190/6366c4c2-a4dc-11e5-8027-617001aefd0c.png)

**Comment by brianr** [comment] 2015-12-18 00:39
Hi @mitchhentges! This is by design; the browser client doesn't know what its IP address is, so it sends that special string to the server (api.rollbar.com) so that the server knows to replace that with the actual remote IP.

If you look in the Rollbar UI, you should see actual IP addresses and not that string. Make sense? I'm going to close this but please reopen if that's not the case.

**Comment by mitchhentges** [comment] 2015-12-18 00:40
I am a skrub, literally just looked at the result online. Many regrets, thanks for the quick response

**Closed by brianr** 2015-12-18 00:39 UTC
