### ISSUE TITLE
rollbar-browser cannot be imported/minified in webpack/babel/uglify

### ISSUE THREAD

**Issue by mrgenixus** [rollbar/rollbar.js#250] opened 2017-02-24 21:24 UTC
I'll try to provide as much information as possible, but the short version is that trying to require rollbar from this package for build using webpack/npm seems to result in the first argument of _wrapNotifierFn being replaced with a reference to require, and runtime errors.

Not sure if this is an issue with the minified source (though I did fork the package to try to supply unminified bundles and get the same result).

Version Info:
- webpack 1.14.0
- uglify-js 2.7.5
- babel 5.8.38

also using [hjs-webpack (7.3.2)](https://github.com/HenrikJoreteg/hjs-webpack/tree/v7.3.2)

babel config:
```
{
  "presets": ["es2015", "react"],
  "env": {
    "development": {
      "presets": ["react-hmre"]
    }
  }
}
```

**Comment by rokob** [comment] 2017-02-24 22:20
I am having trouble reproducing this, I created https://github.com/rokob/simple-rollbar-example to try to have a minimal working example. I am using the same versions of webpack and babel. Mine is running without the hjs-webpack which I can add to see what breaks down, but I don't see anything like what you are seeing. It builds via webpack, and when I open the `dist/index.html` page and click on the div, I see an exception in the console and I see it logged on my Rollbar dashboard (when I put a valid access token in the config).

**Comment by mrgenixus** [comment] 2017-02-25 00:38
This only applies to production builds with minification

**Comment by rokob** [comment] 2017-02-28 21:05
I ran my example with production minification, everything works the same as in the dev build when it comes to catching an exception and seeing it on the Rollbar dashboard.

**Comment by coryvirok** [comment] 2017-06-08 00:48
Closing this out since there hasn't been any activity for a while. Please reopen if this is still a thing.

**Closed by coryvirok** 2017-06-08 00:48 UTC
