### ISSUE TITLE
[node.js] Logs with an Express request object with url that has query params are not being sent 

### ISSUE THREAD

**Issue by andreskeeled** [rollbar/rollbar.js#300] opened 2017-06-02 09:23 UTC
I just upgraded to rollbar 2.0.2.

 While I was changing the code, I noticed I wasn't receiving some errors in Rollbar so I debugged a little. In some requests, **nothing was being sent (and nothing was returning in the callback)**. 

Then, after destructuring the request object and adding one by one the keys (headers, protocol, etc...), I  noticed that **requests with params in the url (e.g.: ?users/?_id=12345) were not being sent.** 

If i removed those params, the request would be sent successfully. I verified this in some POST requests, not sure about the others.

For now, my solution was to send the other keys (headers, protocol, method, body, route) in an object, and the url in the custom data. 

Please look into this,
Thank you

**Comment by coryvirok** [comment] 2017-06-02 16:32
Thanks @andreskeeled. We will get this fixed soon!

**Comment by rokob** [comment] 2017-06-21 00:53
Wow this is a doozy

We use `url.parse(someUrl, true)` in node, that second parameter of true implies

> If true, the query property will always be set to an object returned by the querystring module's parse() method

Going to that documentation for parse, gives us:

> Note: The object returned by the querystring.parse() method does not prototypically inherit from the JavaScript Object. This means that typical Object methods such as obj.toString(), obj.hasOwnProperty(), and others are not defined and will not work.

The problem is that during scrubbing, we use `hasOwnProperty` and that parsed query string ends up inside the object and causes scrubbing to die.

**Comment by rokob** [comment] 2017-06-21 00:54
I have a test that reproduces this, working on a fix.

**Comment by rokob** [comment] 2017-06-21 01:41
And I realized I already fixed this with https://github.com/rollbar/rollbar.js/commit/7eef362c4e1c4ab914e75925895f306f80a69f0f which is in >= 2.0.3, so closing this as it is fixed.

**Closed by rokob** 2017-06-21 01:41 UTC
Labels: bug
