### ISSUE TITLE
`transform` does not receive the original exception object

### ISSUE THREAD

**Issue by rixth** [rollbar/rollbar.js#601] opened 2018-04-24 19:48 UTC
We have exception classes that have additional properties that would aid us in debugging errors. However, only the `message` & `stack` property are captured. I tried using `transform` to manipulate the payload to add these additional fields, but `transform` is not provided with the original exception object.

Could the original error be passed as a second parameter to `transform`, along with the proposed `payload`? Right now, we are abusing the `checkIgnore` function to augment `payload`, as it does receive the original exception.

**Comment by shakiba** [comment] 2018-07-26 18:57
@rixth I [added](https://github.com/rollbar/rollbar.js/commit/7bcb25c2e1e86139af5d217c4098c939b7a1d642) original item as second param passed to `transform()`, I hope that solve this issue.

I will close this issue, please feel free to reopen it if the issue is not resolved.

**Closed by shakiba** 2018-07-26 18:57 UTC
Labels: enhancement
