### ISSUE TITLE
Cannot assign to read only property '_savedStackTrace'

### ISSUE THREAD

**Issue by jirihelmich** [rollbar/rollbar.js#121] opened 2015-08-10 10:52 UTC
`Uncaught TypeError: Cannot assign to read only property '_savedStackTrace' of Malformed public key r._wrapped @ rollbar.min.js:formatted:628`

We use a payment provider library, which contains the code `throw "Malformed public key"`

When rollbar tries to process this "exception", it fails itself.

![image](https://cloud.githubusercontent.com/assets/174768/9169899/9436a95c-3f5e-11e5-833b-e345e7adb786.png)

**Comment by brianr** [comment] 2015-08-10 16:24
Thanks for the report, @jirihelmich.

It looks like the line you highlighted is failing because `e` is a string, not an error object, so setting the `_savedStackTrace` property fails...

**Comment by jirihelmich** [comment] 2015-08-10 16:25
Yes, exactly, they throw a raw string. You should probably handle the case that e is not an object...

**Comment by brianr** [comment] 2015-09-03 21:13
This is fixed in version 1.5.0. You can grab the latest snippet from here: https://rollbar.com/docs/notifier/rollbar.js/ or other distributions from the usual places.

Thanks again for the report!

**Closed by brianr** 2015-09-03 21:13 UTC

**Comment by wcurtis** [comment] 2015-09-09 16:16
Was able to reproduce this in version 1.5.0

Example
```javascript
throw "Test Rollbar 1";
```

Result

![screen shot 2015-09-09 at 12 06 54 pm](https://cloud.githubusercontent.com/assets/530242/9767356/d4d82374-56eb-11e5-9c56-3774dabc3323.png)

Anyone else?

**Comment by coryvirok** [comment] 2015-09-09 18:46
@wcurtis Do you have a publically accessible page that I can test/repro this on? I just tested on rollbar.com and it works properly.

**Comment by wcurtis** [comment] 2015-09-10 22:42
I don't have a public page no, worth noting I had this error within an Ember.js app, not sure if that could be related.
