### ISSUE TITLE
Network telemetry blocks Pusher from subscribing to channels

### ISSUE THREAD

**Issue by EtienneLem** [rollbar/rollbar.js#379] opened 2017-08-16 16:38 UTC
Haven’t been able to find exactly _where_ or _why_ it stops Pusher from working, but setting `autoInstrument: { network: false }` fixes the issue for me.

From what I can tell, the Pusher client still successfully sends XHR requests to my server to get an authentication token for the channels I want to subscribe to (see [Authenticating users](https://pusher.com/docs/authenticating_users)), but the `subscription_succeeded` never gets fired anymore.

Disabling network telemetry isn’t a problem for me, but I thought I’d bring it to your attention nonetheless.

**Comment by emkman** [comment] 2017-08-16 23:04
After upgrading to 2.2, Rollbar broke the callback of the Facebook sdk for us. This broke both login and new user signup for us and fails silently (no error, no console output, nothing logged as a Rollbar item. Shame on me for trusting this would be production ready, but it looks like there are still some serious issues with Telemetry and I question it being enabled by default. Reverting back to 2.1.3 or 2.0.4 both resolved the issue immediately.

**Comment by jessewgibbs** [comment] 2017-08-16 23:25
@EtienneLem @emkman thanks for bringing this to our attention, and sorry for the inconvenience.  We've begun investigating this and will comment on this issue to keep you up-to-date.

**Comment by jessewgibbs** [comment] 2017-08-17 00:09
We've just released [rollbar.js 2.2.1](https://github.com/rollbar/rollbar.js/releases/tag/v2.2.1) to disable the default network instrumentation while we investigate this issue.

**Comment by fraserredmond** [comment] 2017-08-17 00:12
Something similar for us, an XMLHttpRequest.onreadystatechange event wasn't firing - so maybe it's getting overwritten by your event handler.

**Comment by jessewgibbs** [comment] 2017-08-17 00:15
@fraserredmond thanks for the info.  As Etienne mentioned above, you can set `autoInstrument: { network: false } ` to disable the network event capture until we get this sorted out.

**Comment by brianr** [comment] 2017-08-18 23:23
This should be fixed now, as of today's 2.2.3 release. Going to close this issue; see #382 for details of the fix.

@EtienneLem, @emkman, and @fraserredmond - mind trying out the latest version and see if the issue is fixed?

**Closed by brianr** 2017-08-18 23:23 UTC
