### ISSUE TITLE
unknown traceback

### ISSUE THREAD

**Issue by davidmatas** [rollbar/rollbar.js#75] opened 2015-03-12 09:05 UTC
We are having this kind of traceback in our app:

```
TypeError: Cannot read property 'indexOf' of undefined
1 File "(unknown)" line (unknown) in [anonymous]
2 File "(unknown)" line (unknown) in [anonymous]
3 File "(unknown)" line (unknown) in [anonymous]
4 File "(unknown)" line (unknown) in [anonymous]
```

We have Rollbar configured to send additional info (user.id, user.email...) and for some ocurrences in this item that info is empty. But, what drew special attention for us, is the low `runtime_ms`, about 15 miliseconds, so we think that maybe it is related with some expection inside Rollbar code, make sense?

We have also noted these items began to appear at 6th February, date we think it matches with a new version of Rollbar code (v.1.2.0), however we didn't update rollbar snippet that day but a few days later.

**Comment by brianr** [comment] 2015-03-12 09:16
Thanks for the report, @davidmatas . We'll look into this.

I assume no, but any chance you know how to reproduce this?

**Comment by davidmatas** [comment] 2015-03-12 09:28
no :(
We only know it happens for Chrome browser only and in different OS, but we have seen the ocurrences have some level of 'radomly': they don't happen for the same users all the time

**Comment by davidmatas** [comment] 2015-06-09 15:11
ping @brianr

**Comment by brianr** [comment] 2015-06-09 15:20
Thanks for the ping @davidmatas. We think this is fixed in rollbar.js 1.3, which is currently in 'alpha' but should be generally available later this week. I'll update here when that happens.

If you want to try it out now:

- if you're using webpack/browserify/etc., just update your version number to 1.3
- if you're using our standard snippet, replace it with this: https://raw.githubusercontent.com/rollbar/rollbar.js/master/dist/rollbar.snippet.js

**Comment by davidmatas** [comment] 2015-06-09 15:46
Ok @brianr 
So if the error is in rollbar.js why it just began to appear at 6th February? We didn't update our snippet to v1.2 until later, 20th february.

**Comment by brianr** [comment] 2015-06-09 15:53
@davidmatas It's conceivable that 1.2 is related to this, but I would guess that the cause in your case was actually that you made some change to your app which exposed this bug for you. That would also explain why you saw this before you updated your snippet to use 1.2.

**Comment by brianr** [comment] 2015-06-19 18:24
@davidmatas We've released 1.3.0 - I *believe* this issue should be fixed there. Can you verify when you get the chance?

I'm going to close this issue for now for housekeeping purposes, but please reopen if you still get tracebacks like these in 1.3.

**Closed by brianr** 2015-06-19 18:24 UTC

**Comment by davidmatas** [comment] 2015-06-23 14:50
Finally with the update we think we have found the problem, it is a Chrome extension interacting with Mootools

Thanks!

**Comment by coryvirok** [comment] 2015-06-23 17:14
Thanks for following up, David.

Which extension was causing this? If I hear about similar issues I'll let customers know.

**Comment by gauravjantwal** [comment] 2017-11-08 10:10
Hey @davidmatas, as @coryvirok asked, have same question, what extension was causing this issue at your end? Would be helpful, as we too observing the same issue:

`(unknown): Not a Product`
`File "(unknown)" line (unknown) col 0 in [anonymous]`

**Comment by sankalpsans** [comment] 2018-06-18 09:21
We have noticed this on Safari Desktop as well.
Based on my experience, "PDF Viewer" seems to be the only common extension amongst all the browsers that have reported this issue.
