### ISSUE TITLE
Dependency on window.* variables causing issues.

### ISSUE THREAD

**Issue by staxmanade** [rollbar/rollbar.js#141] opened 2015-09-28 21:43 UTC
Investigating the use of Rollbar for a JS project (that is not in a browser) and running into some specific issues with how Rollbar depends heavily on the `window` global.

Accessing any of the below will not work in certain environments.

```
window.onerror
window.console
window.location.href
window.location.search
window.navigator.userAgent
window.navigator.language
window.navigator.cookieEnabled
window.screen.width
window.screen.height
window.navigator.plugins
```

A good approach would be to abstract the usages above into something that we could provide implementations for.
#57 also calls out the dependency on `window`

**Comment by Crisfole** [comment] 2015-09-29 11:27
There's a UMD version of Rollbar designed to fix exactly this issue. Any of the files in https://github.com/rollbar/rollbar.js/tree/master/dist with `.umd.` in the filename will do the trick!

**Comment by Crisfole** [comment] 2015-09-30 13:50
Looks like the UMD version actually gets this wrong. You're correct.

**Comment by Crisfole** [comment] 2015-10-01 15:01
Rollbar.js also depends on `document` and `navigator` https://github.com/rollbar/rollbar.js/blob/master/dist/rollbar.umd.nojson.js#L917-L923

**Comment by bwigoder** [comment] 2015-10-01 15:14
I haven't been able to get rollbar playing nicely with Firefox, due to its reliance on the 'window' and 'document' variables.

Any feedback would be greatly appreciated.

**Comment by brianr** [comment] 2015-10-01 22:43
@bwigoder Can you tell us more? We test this library in Firefox, and the tests are passing...

**Comment by bwigoder** [comment] 2015-10-02 10:40
@brianr - Sorry, I wasn't clear. The issue is when building a Firefox Extension using their Addon SDK, and aiming to integrate rollbar.js for client-side error tracking.

**Comment by elliottheis** [comment] 2015-10-21 18:55
@Crisfole @brianr I'm also being bitten by this issue which ultimately is preventing me from shipping Rollbar support out to production. Is the intent for the UMD module to be completely self-contained / isolated in scope?

**Comment by lehresman** [comment] 2017-02-13 15:56
I have verified that the UMD version does indeed still contain references to `document` and `window`. @coryvirok and @rokob thoughts?

**Comment by rokob** [comment] 2017-02-13 20:34
So this is definitely an issue, but the fix is not as simple as passing in the window and document to the IIFE in the UMD version. That may work in browser contexts, but the non-browser contexts would most likely still not work correctly which would lead to just different issues. The plan is to make this library truly universal by unifying this library with https://github.com/rollbar/node_rollbar and handling the dependencies on the globals properly.

**Comment by rokob** [comment] 2017-02-17 22:02
I am working on making this library actually work on both the server and in the browser. In doing so, I will make sure we have a documented way to use it in an isomorphic application. The tracking issue for this work is: #248

**Comment by coryvirok** [comment] 2017-06-08 00:57
Closing this out since the universal branch was merged.

**Closed by coryvirok** 2017-06-08 00:57 UTC
Labels: enhancement
