### ISSUE TITLE
Lambda wrapper handler capture timeouts

### ISSUE THREAD

**Issue by mledom** [rollbar/rollbar.js#585] opened 2018-03-08 03:54 UTC
The lambda handler wrapper should be able to capture timeouts. There is probably a couple different ways to accomplish but the basic idea would be to check the context for the timeout value and some time before the timeout (maybe configurable) the wrapper timeout would fire and either fire a Rollbar timeout error or a custom callback.

Similar ideas found here:
https://www.stackery.io/blog/handling-serverless-function-timeouts/
https://blog.precogs.com/precogs-lambda-race-250f349c3641

**Comment by vincentkwok** [comment] 2018-06-25 07:59
Agree, any news?

**Comment by rivkahstandig3636** [comment] 2018-06-25 10:21
This is scheduled to be addressed in the next release.

**Comment by rokob** [comment] 2018-06-27 19:06
Sure I can do this, watchdogs are inherently racy which is why AWS suggests using a step function which listens on the error queue for timeouts and calls a different lambda function which can then report the error somewhere else. It is a bit convoluted but more reliable. There is no guarantee that the watchdog report is correct (your function finishes within the remaining time) nor that the report makes it out (network issues are the cause of function being slow which means the call to rollbar might not finish in the remaining time). But nonetheless this is an easy thing to do and we can make it configurable.

**Closed** 2018-06-29 17:57 UTC
Labels: enhancement
