### ISSUE TITLE
Chrome 43, 1.3.0: Uncaught TypeError: a.loadFull is not a function

### ISSUE THREAD

**Issue by LouisStAmour** [rollbar/rollbar.js#98] opened 2015-06-22 17:06 UTC
Not sure why/how this is happening, but "loadFull" isn't defined anywhere else in my codebase and the stack trace refers to line 14 of an anonymous JS block, which is where my Rollbar code lies. It seems to so far have occurred only when someone is actually signed in, am I doing something wrong? :)

It only started once I updated to 1.3.0 this weekend. 1.2.3 worked for me previously, so maybe I'll rollback to that.

```ruby
<script>
    var _rollbarConfig = {
        accessToken: "<%= ENV['ROLLBAR_CLIENT_ACCESS_TOKEN'] || '' %>",
        captureUncaught: true,
        payload: {
            environment: "<%== j Rails.env %>"<% if current_refinery_user.present? %>,
            person: {
                id: "<%== j current_refinery_user.id.to_s %>",
                username: "<%== j current_refinery_user.username %>",
                email: "<%== j current_refinery_user.email %>",
            }<% end %>
        }
    };
    !function(r){function o(e){if(t[e])return t[e].exports;var n=t[e]={exports:{},id:e,loaded:!1};return r[e].call(n.exports,n,n.exports,o),n.loaded=!0,n.exports}var t={};return o.m=r,o.c=t,o.p="",o(0)}([function(r,o,t){"use strict";var e=t(1).Rollbar,n=t(2),i="https://d37gvrvc0wt4s1.cloudfront.net/js/v1.3/rollbar.umd.min.js";_rollbarConfig.rollbarJsUrl=_rollbarConfig.rollbarJsUrl||i;var a=e.init(window,_rollbarConfig),l=n(a,_rollbarConfig);a.loadFull(window,document,!1,_rollbarConfig,l)},function(r,o,t){"use strict";function e(r){this.shimId=++s,this.notifier=null,this.parentShim=r,this.logger=function(){},window.console&&void 0===window.console.shimId&&(this.logger=window.console.log)}function n(r,o,t){window._rollbarWrappedError&&(t[4]||(t[4]=window._rollbarWrappedError),t[5]||(t[5]=window._rollbarWrappedError._rollbarContext),window._rollbarWrappedError=null),r.uncaughtError.apply(r,t),o&&o.apply(window,t)}function i(r){var o=e;return l(function(){if(this.notifier)return this.notifier[r].apply(this.notifier,arguments);var t=this,e="scope"===r;e&&(t=new o(this));var n=Array.prototype.slice.call(arguments,0),i={shim:t,method:r,args:n,ts:new Date};return window._rollbarShimQueue.push(i),e?t:void 0})}function a(r,o){if(o.hasOwnProperty&&o.hasOwnProperty("addEventListener")){var t=o.addEventListener;o.addEventListener=function(o,e,n){t.call(this,o,r.wrap(e),n)};var e=o.removeEventListener;o.removeEventListener=function(r,o,t){e.call(this,r,o&&o._wrapped?o._wrapped:o,t)}}}function l(r,o){return o=o||window.console.log||function(){},function(){try{return r.apply(this,arguments)}catch(t){o("Rollbar internal error:",t)}}}var s=0;e.init=function(r,o){var t=o.globalAlias||"Rollbar";if("object"==typeof r[t])return r[t];r._rollbarShimQueue=[],r._rollbarWrappedError=null,o=o||{};var i=new e;return l(function(){if(i.configure(o),o.captureUncaught){var e=r.onerror;r.onerror=function(){var r=Array.prototype.slice.call(arguments,0);n(i,e,r)};var l,s,u="EventTarget,Window,Node,ApplicationCache,AudioTrackList,ChannelMergerNode,CryptoOperation,EventSource,FileReader,HTMLUnknownElement,IDBDatabase,IDBRequest,IDBTransaction,KeyOperation,MediaController,MessagePort,ModalWindow,Notification,SVGElementInstance,Screen,TextTrack,TextTrackCue,TextTrackList,WebSocket,WebSocketWorker,Worker,XMLHttpRequest,XMLHttpRequestEventTarget,XMLHttpRequestUpload".split(",");for(l=0;l<u.length;++l)s=u[l],r[s]&&r[s].prototype&&a(i,r[s].prototype)}return r[t]=i,i},i.logger)()},e.prototype.loadFull=function(r,o,t,e,n){var i=l(function(){var r=o.createElement("script"),n=o.getElementsByTagName("script")[0];r.src=e.rollbarJsUrl,r.async=!t,r.onload=a,n.parentNode.insertBefore(r,n)},this.logger),a=l(function(){var o;if(void 0===r._rollbarPayloadQueue){var t,e,i,a;for(o=new Error("rollbar.js did not load");t=r._rollbarShimQueue.shift();)for(i=t.args,a=0;a<i.length;++a)if(e=i[a],"function"==typeof e){e(o);break}}"function"==typeof n&&n(o)},this.logger);l(function(){t?i():r.addEventListener?r.addEventListener("load",i,!1):r.attachEvent("onload",i)},this.logger)()},e.prototype.wrap=function(r,o){try{var t;if(t="function"==typeof o?o:function(){return o||{}},"function"!=typeof r)return r;if(r._isWrap)return r;if(!r._wrapped){r._wrapped=function(){try{return r.apply(this,arguments)}catch(o){throw o._rollbarContext=t()||{},o._rollbarContext._wrappedSource=r.toString(),window._rollbarWrappedError=o,o}},r._wrapped._isWrap=!0;for(var e in r)r.hasOwnProperty(e)&&(r._wrapped[e]=r[e])}return r._wrapped}catch(n){return r}};for(var u="log,debug,info,warn,warning,error,critical,global,configure,scope,uncaughtError".split(","),p=0;p<u.length;++p)e.prototype[u[p]]=i(u[p]);r.exports={Rollbar:e,_rollbarWindowOnError:n}},function(r,o,t){"use strict";r.exports=function(r,o){return function(t){if(!t&&!window._rollbarInitialized){var e=window.RollbarNotifier,n=o||{},i=n.globalAlias||"Rollbar",a=window.Rollbar.init(n,r);a._processShimQueue(window._rollbarShimQueue||[]),window[i]=a,window._rollbarInitialized=!0,e.processPayloads()}}}}]);
</script>
```

```
TypeError: a.loadFull is not a function
1. File my-code.js line 2 col 28781 in null.<anonymous>
2. File my-code.js line 2 col 27248 in st.fn.extend.append
3. File my-code.js line 2 col 29797 in st.fn.extend.domManip
4. File my-code.js line 1 col 13834 in Function.st.extend.globalEval
5. File my-code.js line 1 col 13823 in [anonymous]
6. File "(native)" line (unknown) in eval
7. File "<anonymous>" line 14 col 203 in eval
8. File "<anonymous>" line 14 col 198 in eval
9. File "<anonymous>" line 14 col 111 in o
10. File "<anonymous>" line 14 col 448 in Object.eval
```

**Comment by coryvirok** [comment] 2015-06-22 17:43
Hi Louis,

I just tried to repro this with your code but wasn't able to. Could it be that `current_refinery_user.present?` is false and causing `_rollbarConfig` to be invalid JSON?

Are you seeing any other JS errors in your dev console?

Here's a working example:

```html
<html>
<head>
<script>
    var _rollbarConfig = {
        accessToken: "ASDF",
        captureUncaught: true,
        payload: {
            environment: "test",
            person: {
                id: "1",
                username: "cory",
                email: "cory@rollbar.com"
            }
        }
    };
    !function(r){function o(e){if(t[e])return t[e].exports;var n=t[e]={exports:{},id:e,loaded:!1};return r[e].call(n.exports,n,n.exports,o),n.loaded=!0,n.exports}var t={};return o.m=r,o.c=t,o.p="",o(0)}([function(r,o,t){"use strict";var e=t(1).Rollbar,n=t(2),i="https://d37gvrvc0wt4s1.cloudfront.net/js/v1.3/rollbar.umd.min.js";_rollbarConfig.rollbarJsUrl=_rollbarConfig.rollbarJsUrl||i;var a=e.init(window,_rollbarConfig),l=n(a,_rollbarConfig);a.loadFull(window,document,!1,_rollbarConfig,l)},function(r,o,t){"use strict";function e(r){this.shimId=++s,this.notifier=null,this.parentShim=r,this.logger=function(){},window.console&&void 0===window.console.shimId&&(this.logger=window.console.log)}function n(r,o,t){window._rollbarWrappedError&&(t[4]||(t[4]=window._rollbarWrappedError),t[5]||(t[5]=window._rollbarWrappedError._rollbarContext),window._rollbarWrappedError=null),r.uncaughtError.apply(r,t),o&&o.apply(window,t)}function i(r){var o=e;return l(function(){if(this.notifier)return this.notifier[r].apply(this.notifier,arguments);var t=this,e="scope"===r;e&&(t=new o(this));var n=Array.prototype.slice.call(arguments,0),i={shim:t,method:r,args:n,ts:new Date};return window._rollbarShimQueue.push(i),e?t:void 0})}function a(r,o){if(o.hasOwnProperty&&o.hasOwnProperty("addEventListener")){var t=o.addEventListener;o.addEventListener=function(o,e,n){t.call(this,o,r.wrap(e),n)};var e=o.removeEventListener;o.removeEventListener=function(r,o,t){e.call(this,r,o&&o._wrapped?o._wrapped:o,t)}}}function l(r,o){return o=o||window.console.log||function(){},function(){try{return r.apply(this,arguments)}catch(t){o("Rollbar internal error:",t)}}}var s=0;e.init=function(r,o){var t=o.globalAlias||"Rollbar";if("object"==typeof r[t])return r[t];r._rollbarShimQueue=[],r._rollbarWrappedError=null,o=o||{};var i=new e;return l(function(){if(i.configure(o),o.captureUncaught){var e=r.onerror;r.onerror=function(){var r=Array.prototype.slice.call(arguments,0);n(i,e,r)};var l,s,u="EventTarget,Window,Node,ApplicationCache,AudioTrackList,ChannelMergerNode,CryptoOperation,EventSource,FileReader,HTMLUnknownElement,IDBDatabase,IDBRequest,IDBTransaction,KeyOperation,MediaController,MessagePort,ModalWindow,Notification,SVGElementInstance,Screen,TextTrack,TextTrackCue,TextTrackList,WebSocket,WebSocketWorker,Worker,XMLHttpRequest,XMLHttpRequestEventTarget,XMLHttpRequestUpload".split(",");for(l=0;l<u.length;++l)s=u[l],r[s]&&r[s].prototype&&a(i,r[s].prototype)}return r[t]=i,i},i.logger)()},e.prototype.loadFull=function(r,o,t,e,n){var i=l(function(){var r=o.createElement("script"),n=o.getElementsByTagName("script")[0];r.src=e.rollbarJsUrl,r.async=!t,r.onload=a,n.parentNode.insertBefore(r,n)},this.logger),a=l(function(){var o;if(void 0===r._rollbarPayloadQueue){var t,e,i,a;for(o=new Error("rollbar.js did not load");t=r._rollbarShimQueue.shift();)for(i=t.args,a=0;a<i.length;++a)if(e=i[a],"function"==typeof e){e(o);break}}"function"==typeof n&&n(o)},this.logger);l(function(){t?i():r.addEventListener?r.addEventListener("load",i,!1):r.attachEvent("onload",i)},this.logger)()},e.prototype.wrap=function(r,o){try{var t;if(t="function"==typeof o?o:function(){return o||{}},"function"!=typeof r)return r;if(r._isWrap)return r;if(!r._wrapped){r._wrapped=function(){try{return r.apply(this,arguments)}catch(o){throw o._rollbarContext=t()||{},o._rollbarContext._wrappedSource=r.toString(),window._rollbarWrappedError=o,o}},r._wrapped._isWrap=!0;for(var e in r)r.hasOwnProperty(e)&&(r._wrapped[e]=r[e])}return r._wrapped}catch(n){return r}};for(var u="log,debug,info,warn,warning,error,critical,global,configure,scope,uncaughtError".split(","),p=0;p<u.length;++p)e.prototype[u[p]]=i(u[p]);r.exports={Rollbar:e,_rollbarWindowOnError:n}},function(r,o,t){"use strict";r.exports=function(r,o){return function(t){if(!t&&!window._rollbarInitialized){var e=window.RollbarNotifier,n=o||{},i=n.globalAlias||"Rollbar",a=window.Rollbar.init(n,r);a._processShimQueue(window._rollbarShimQueue||[]),window[i]=a,window._rollbarInitialized=!0,e.processPayloads()}}}}]);
</script>
</head>
<body>Hi</body></html>
```

**Comment by LouisStAmour** [comment] 2015-06-22 22:00
I know it's a weird bug in that other users aren't seeing it. The JSON is valid, and it does report correctly -- but the bug I see in Rollbar has a backtrace and message referring to this error and not the actual error I'd perhaps need to track down. I'm not sure yet what's going on, maybe some kind of naming collision? I'll try to investigate and reproduce it locally some point soon.

**Comment by coryvirok** [comment] 2015-06-22 22:15
Oh, you're seeing that something is being reported? Can you link me to your
Rollbar project or the item page for the error you're seeing in Rollbar?


Cory Virok, @coryvirok <http://twitter.com/coryvirok>
Co-founder and CTO, Rollbar <http://rollbar.com/>

**Comment by LouisStAmour** [comment] 2015-06-22 23:01
Just a quick reply by email from my phone, but I only have the one project on Rollbar, my username is "louisstamour". I suspect a few recent JS errors might be related, but loadFull was the one that jumped out at me first.


Louis.

**Comment by LouisStAmour** [comment] 2015-06-24 04:56
I ended up rolling back to the rollbar 1.2.3 snippet. I was getting a .length is undefined error that kept pointing me at the rollbar snippet. I figured this was coincidence, except when I turned off the rollbar snippet, no such errors appeared in the console in Chrome. Frankly, given that most of the time, I couldn't get a good fix on the errors anyway due to Chrome's security policies and the issues being in third-party libraries or Google Maps, I'm not sure Rollbar's JS support matters much to me. At this point, I only really pay attention to Rails errors, and error reporting you ignore is ... well, just as terrible as not having it in the first place, isn't it...

**Comment by LouisStAmour** [comment] 2015-06-30 17:57
Updated to 1.4.2 and I'm still seeing "TypeError: i.loadFull is not a function"

It appears to be triggered by an PJAX function receiving the wrong HTML -- a full page including this script -- and inserting all of it in the page, causing errors. It wasn't noticed as easily because on error, the PJAX script would reload the page's URL. It also didn't happen on every request, only a few malformed responses.

I was seeing a lot of Unknown Script errors that were the same error -- I simply had to move the Rollbar script higher than the meta tags that some legacy code attached JavaScript to (sigh).

I still haven't pinned down exactly why this error is occurring, but at least I can reproduce it locally. And I can workaround it. It appears to be rare enough that if I encounter it in future, PJAX will be the first thing I think of. :)

**Comment by coryvirok** [comment] 2015-09-01 00:39
Thanks for the info, Louis.

I'm not familiar with PJAX and how it could cause this error. If you can still repro it, I'd love to take another look.

**Comment by LouisStAmour** [comment] 2015-09-01 20:31
PJAX means returning partial HTML responses and replacing part of the page with the response. It's a Page-variant of AJAX, hence the P-. It was commonly used with Rails apps to speed them up while still rendering the HTML in Ruby instead of with JavaScript.

Normally you'd receive just the HTML needed for the middle of the page, the contents of a body tag, for example. But with a malformed response, the entire HTML was being returned in the AJAX (PJAX) call, including a new head tag, title tag, script tag for rollbar, and body tag. This was then inserted, and errors ensued.

Fixing such responses eliminated at least the errors I was seeing in Rollbar as caused by Rollbar itself. I don't think I tried it, but maybe loading Rollbar twice, after onload, causes the issue? Just a guess.

**Comment by coryvirok** [comment] 2015-09-01 23:59
Oooooh, right. Ya that'd do it. 

I bet what was happening was the snippet was included twice and attempting to call `Rollbar.loadFull()` which would have been removed since the full source of the notifier had already been loaded.

I suppose the change we could make is to handle multiple snippets gracefully.

Thanks for the info!

**Comment by coryvirok** [comment] 2015-09-01 23:59
Also, I'm going to close this since it appears the problem has been resolved. If you disagree, please re-open.

**Closed by coryvirok** 2015-09-01 23:59 UTC

**Comment by efreed** [comment] 2015-12-22 22:38
This came up for me today.  It was because the rollbar snippet was included twice in the page, removing one of them fixed it.

**Comment by kirkchris** [comment] 2016-11-17 03:01
@efreed thanks for mentioning that. we hit this today because we had loaded rollbar and then accidentally also left it enabled via segment. exactly the cause! made it a quick fix ;)

**Comment by pccjamie** [comment] 2017-03-02 21:28
I'm experiencing this issue as well. Only occurs when I run my unit tests. And it's while using `ng-rollbar`

```
 Error: [$injector:modulerr] Failed to instantiate module my_module_name due to:
    TypeError: a.loadFull is not a function
        at Object.<anonymous> (bower_components/ng-rollbar/ng-rollbar.js:32:444)
```
I've opened an issue with that repo owner, but thought I'd mention it here as well.

Otherwise, my errors are sent to Rollbar just fine.

**Comment by jasongornall** [comment] 2017-05-31 08:13
getting it too woot

**Comment by christophmegusta** [comment] 2017-11-13 12:42
we are getting

```
application start failed in state init: Error: [$injector:modulerr] Failed to instantiate module the.app due to:
TypeError: Cannot read property 'loadFull' of undefined
    at Object.<anonymous> (http://localhost:31234/lib/ng-rollbar/ng-rollbar.min.js:6:1548)
    at b (http://localhost:31234/lib/ng-rollbar/ng-rollbar.min.js:6:1199)
    at http://localhost:31234/lib/ng-rollbar/ng-rollbar.min.js:6:1286
    at Object.init (http://localhost:31234/lib/ng-rollbar/ng-rollbar.min.js:6:1291)
```
